dataSources:
  ds0:
    driverClassName: com.mysql.jdbc.Driver
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    jdbcUrl: jdbc:mysql://localhost:3306/ds0
    username: root
    password: PasswordYash@1

  ds1:
    driverClassName: com.mysql.jdbc.Driver
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    jdbcUrl: jdbc:mysql://localhost:3306/ds1
    username: root
    password: PasswordYash@1

rules:
- !SHARDING
    tables:
      t:
        actualDataNodes : ds${0..1}.t
        databaseStrategy :
          standard:
            shardingColumn: ID
            shardingAlgorithmName: mod
        keyGenerateStrategy:
          column: ID
          keyGeneratorName: snowflake
    shardingAlgorithms:
      mod:
        type: INLINE
        props:
          algorithm-expression : ds${ID%5%2}
    keyGenerators :
      snowflake :
        type : SNOWFLAKE

props:
  show-sql :  true
